squash me

diff --git a/lib/orchestrator/stages/terraform/ctl b/lib/orchestrator/stages/terraform/ctl
--- a/lib/orchestrator/stages/terraform/ctl
+++ b/lib/orchestrator/stages/terraform/ctl
@@ -11,12 +11,13 @@ this_dir="$(dirname "$(readlink -f "$0")")"
 function main() {
   cmd="${1:?}"
 
-	: ${STAGE_NAME:?}
-	: ${OUTPUT_DIR:?}
-	: ${GENFILES:?}
-	: ${INTERACTIVE:=true}
+  : ${STAGE_NAME:?}
+  : ${OUTPUT_DIR:?}
+  : ${GENFILES:?}
+  : ${INTERACTIVE:=true}
 
-	local stage_output_dir="$OUTPUT_DIR/$STAGE_NAME"
+  local stage_stamp_dir="$GENFILES/$STAGE_NAME"
+  local stage_output_dir="$OUTPUT_DIR/$STAGE_NAME"
 
   case "$cmd" in
     up|down) "cmd_$cmd" ;;
@@ -28,32 +29,42 @@ function common_init() {
   if [ -e "$stage_output_dir/.terraform.lock.hcl" ]; then
     cp -at ./ "$stage_output_dir/.terraform.lock.hcl"
   fi
-  terraform init $( [[ "$INTERACTIVE" != false ]] || echo '-input=false' )
+  (
+    cd "$stage_stamp_dir"
+    terraform init $( [[ "$INTERACTIVE" != false ]] || echo '-input=false' )
+  )
   cp -at "$stage_output_dir" ".terraform.lock.hcl"
 }
 
 function cmd_up() {
-	common_init
+  common_init
 
-  local outfile="$stage_output_dir/output.json"
-	echo "Running 'terraform apply'"
-	terraform apply \
-    $( [[ "$INTERACTIVE" != false ]] || echo '-input=false -auto-approve' )
-	echo "Running 'terraform output -json'"
-	if terraform output -json > "${outfile}.tmp"; then
-		mv "${outfile}.tmp" "$outfile"
-	else
-		echo "Error: output saved in ${outfile}.tmp" >&2
-		exit 1
-	fi
+  (
+    cd "$stage_stamp_dir"
+
+    local outfile="$stage_output_dir/output.json"
+    echo "Running 'terraform apply'"
+    terraform apply \
+      $( [[ "$INTERACTIVE" != false ]] || echo '-input=false -auto-approve' )
+    echo "Running 'terraform output -json'"
+    if terraform output -json > "${outfile}.tmp"; then
+      mv "${outfile}.tmp" "$outfile"
+    else
+      echo "Error: output saved in ${outfile}.tmp" >&2
+      exit 1
+    fi
+  )
 }
 
 function cmd_down() {
-	common_init
+  common_init
 
-	echo "Running 'terraform destroy'"
-	terraform destroy \
-    $( [[ "$INTERACTIVE" != false ]] || echo '-input=false -auto-approve' )
+  (
+    cd "$stage_stamp_dir"
+    echo "Running 'terraform destroy'"
+    terraform destroy \
+      $( [[ "$INTERACTIVE" != false ]] || echo '-input=false -auto-approve' )
+  )
 }
 
 main "$@"
